csv_file: "data/data.csv"
batch_size: 2048
k_fold: 10
alpha: [10, 0.0000001]
# max_epochs: 2000

channels: [4, 64, 128, 32, 16, 2]
lr: 0.0003
weight_decay: 0
patience: 15

name: "mlp_l"
model_name: "LitMLP"
