csv_file: "data/data.csv"
batch_size: 2048
k_fold: 10
alpha: [10, 0.0000001]
# max_epochs: 2000

in_channel: 4
out_channel: 2
d_model: 128
n_head: 8
dim_feedforward: 512
norm_first: False
num_layer: 6

lr: 0.0003
weight_decay: 0
patience: 15

name: "tf_l"
model_name: "LitTF"
